services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
    - ./auth_service:/app

  marketplace_service:
    build:
      context: ./marketplace_service
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app

volumes:
  postgres_data: